mod auth;
mod course;
mod user;
mod notification;   
mod wishlist;
mod instructor;
mod learning;
mod ai;
mod admin;
mod withdrawal;

pub use auth::auth_routes;
pub use course::course_routes;
pub use user::user_routes;
pub use notification::notification_routes; 
pub use wishlist::wishlist_routes;
pub use course::order_routes;
pub use course::review_routes;
pub use instructor::instructor_routes;
pub use learning::learning_routes;
pub use ai::ai_routes;
pub use admin::admin_routes;
pub use withdrawal::withdrawal_routes;